---
apiVersion: v1
kind: Pod
metadata:
  name: g729-codec-service
  labels:
    app: g729-codec-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g729-codec-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  containers:
    - name: g729-codec-service
      image: <image-location>
      ports:
        - containerPort: 9001
          protocol: TCP
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: g729-codec-service
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: g729-codec-service
  type: ClusterIP
---
